### ISSUE TITLE
nethogs: invalid option -- 'v'

### ISSUE THREAD

**Issue by Rudloff** [akshayKMR/hogwatch#12]
Hello,

I am trying to use hogwatch 0.1.7 with nethogs 0.8.0 and I get this error:
`nethogs: invalid option -- 'v'`

The webview does not display any data:
![capture d ecran - 16062016 - 01 41 56](https://cloud.githubusercontent.com/assets/840125/16101125/86930d32-3363-11e6-92da-e9a8ad4ecca2.png)

**Comment by akshaykmr** [comment]
Some distro repositories have nethogs version 0.8.0. update it nethogs to 0.8.2+ or you may [build it from source](https://github.com/raboof/nethogs#building-from-source).
