### ISSUE TITLE
Webview Broken 

### ISSUE THREAD

**Issue by pik** [akshayKMR/hogwatch#13]
Not sure what it's usually supposed to look like but `$('#charts').highcharts()` returns `undefined` 

![screenshot from 2017-05-14 16-10-29](https://cloud.githubusercontent.com/assets/10236920/26037752/ebca2dfe-38bf-11e7-8bb0-e19f4d9bf5d0.png)

**Comment by akshaykmr** [comment]
I think this error was fixed while I did some housekeeping earlier. If anyone comes across this error feel free to reopen this thread.
