### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by abdalmoniem** [akshayKMR/hogwatch#14]
`sudo hogwatch` fails with the following error:

**`error: [Errno 98] Address already in use: ('0.0.0.0', 6432)`**

here is a screenshot of the error:

![screenshot from 2017-11-12 06 37 46](https://user-images.githubusercontent.com/11904264/32696030-0d3f930e-c775-11e7-8561-ba57ee9444d5.png)

**Comment by akshaykmr** [comment]
The bottle web server in hogwatch binds itself to port `6432`.
Failure can mean that there is another process using that port or maybe a previous instance for hogwatch didn't quit properly.
You will have to check that, also ensure that you are using nethogs `0.8.2 +`

Might be worth trying to run the app in server only mode with a different port with `sudo hogwatch server 9000` and viewing it in your browser `localhost:9000`


I do not maintain this software. I made it for a college assignment.

**Comment by abdalmoniem** [comment]
ok, solved, it didn't quit properly as you said.
