### ISSUE TITLE
Process Names not showing in web view but they are visible in browser!

### ISSUE THREAD

**Issue by amanmj** [akshayKMR/hogwatch#4]
Names of processes are not being listed in webview when `sudo ./hogwatch` is executed.

<br>
![screenshot from 2016-04-30 23-52-57](https://cloud.githubusercontent.com/assets/7460559/14937747/b336a92e-0f2e-11e6-8e1b-ba8fe43c4a73.png)

<br>
Where as when `http://localhost:6432/index.html` is opened in browser, the process names are visible.

<br>
![screenshot from 2016-04-30 23-53-48](https://cloud.githubusercontent.com/assets/7460559/14937752/e73f9ad2-0f2e-11e6-8908-e623a848e177.png)

**Comment by akshaykmr** [comment]
This issue is related to the webview and it's renderer which is diffcult to test for with different platforms.
[Reference](https://github.com/r0x0r/pywebview#what-web-renderer-is-used)
