### ISSUE TITLE
remove `dist` folder and use github releases and tagging instead

### ISSUE THREAD

**Issue by frans-fuerst** [akshayKMR/hogwatch#8]
With `git` it's easy to get back to reproducible source trees using tags and GitHub provides Releases with the ability to add binaries. Adding releases to the source tree is unnecessary and it makes repositories larger and longer to clone (currently 13 out of 16MB are used for binaries)

**Comment by akshaykmr** [comment]
Done. Had to force push the changes to remove dist from previous commits as well. I suppose anyone who has forked/clone must work on a fresh copy? 
PS: I won't be active in this month because of my finals.
