### ISSUE TITLE
packaging suggestions

### ISSUE THREAD

**Issue by brbsix** [akshayKMR/hogwatch#9]
Just a few suggestions if you get around to it:
1.  Rename _application_ directory to _hogwatch_. Otherwise you'll just see an import named _application_ or a directory named _application_ in _${exec_prefix}/lib/python<version>/site-packages_ and it's not really clear what package it belongs to.
2.  Add _build_, _hogwatch.egg-info_, and _MANIFEST_ to _.gitignore_. These are part of the build/packaging process and should not be committed or modified.
3.  Delete _README.txt_ or add `exclude README.txt` to _MANIFEST.in_ (otherwise it will be included in the package).
4.  _application/.gitignore_ and _application/server/static/.gitignore_ don't seem to serve any purpose and should be consolidated into the main _.gitignore_. If you end up keeping them, exclude them in _MANIFEST.in_ so that they don't get packaged.

**Comment by akshaykmr** [comment]
2,3 and 4 done. Will address point 1 later since the start script and application folder would have the same name in in the project root.
Thanks!

**Comment by brbsix** [comment]
Cool, great. Also, in case you're interested I just submitted a PR #11 for an easy way to rename the application folder (just move `hogwatch` script into `bin` directory).
